**Question1**

Create a function that takes an integer and returns a list from 1 to the given number, where:

1. If the number can be divided evenly by 4, amplify it by 10 (i.e. return 10 times the
number).

2. If the number cannot be divided evenly by 4, simply return the number.
Examples

amplify(4) ➞ [1, 2, 3, 40]

amplify(3) ➞ [1, 2, 3]

amplify(25) ➞ [1, 2, 3, 40, 5, 6, 7, 80, 9, 10, 11, 120, 13, 14, 15, 160,
17, 18, 19, 200, 21, 22, 23, 240, 25]

Notes

 The given integer will always be equal to or greater than 1.

 Include the number (see example above).

 To perform this problem with its intended purpose, try doing it with list
comprehensions. If that&#39;s too difficult, just solve the challenge any way you can.

In [12]:
def amplify(num):
  return[i*10 if i%4 == 0 else i for i in range(num+1) ]


print(f'amplify(4)➞ {amplify(4)}')
print(f'amplify(3)➞ {amplify(3)}')
print(f'amplify(25)➞ {amplify(25)}')

amplify(4)➞ [0, 1, 2, 3, 40]
amplify(3)➞ [0, 1, 2, 3]
amplify(25)➞ [0, 1, 2, 3, 40, 5, 6, 7, 80, 9, 10, 11, 120, 13, 14, 15, 160, 17, 18, 19, 200, 21, 22, 23, 240, 25]


**Question2**

Create a function that takes a list of numbers and return the number that&#39;s unique.

Examples

unique([3, 3, 3, 7, 3, 3]) ➞ 7

unique([0, 0, 0.77, 0, 0]) ➞ 0.77

unique([0, 1, 1, 1, 1, 1, 1, 1]) ➞ 0

Notes

Test cases will always have exactly one unique number while all others are the same.

In [13]:
def unique(lst):
  count={}
  for i in lst:
    if i in count:
      count[i]+=1
    else:
      count[i]=1
  for i, num in count.items():
    if(num==1):
     print(i)



unique([3, 3, 3, 7, 3, 3])

unique([0, 0, 0.77, 0, 0])

unique([0, 1, 1, 1, 1, 1, 1, 1])

7
0.77
0


**Question3**

Your task is to create a Circle constructor that creates a circle with a radius provided by an
argument. The circles constructed must have two getters getArea() (PIr^2) and
getPerimeter() (2PI*r) which give both respective areas and perimeter (circumference).

For help with this class, I have provided you with a Rectangle constructor which you can use
as a base example.

Examples

circy = Circle(11)
circy.getArea()
 Should return 380.132711084365
circy = Circle(4.44)
circy.getPerimeter()
 Should return 27.897342763877365
Notes
Round results up to the nearest integer.

In [22]:
from math import pi
def getArea(r):
  return pi*pow(r,2)
def getPerimeter(r):
  return 2*pi*r

print(f'getArea(11) ->{getArea(11)}')
print(f'getPerimeter(4.44) ->{getPerimeter(4.44)}')

getArea(11) ->380.132711084365
getPerimeter(4.44) ->27.897342763877365


**Question4**

Create a function that takes a list of strings and return a list, sorted from shortest to longest.

Examples

sort_by_length([&quot;Google&quot;, &quot;Apple&quot;, &quot;Microsoft&quot;])
➞ [&quot;Apple&quot;, &quot;Google&quot;, &quot;Microsoft&quot;]

sort_by_length([&quot;Leonardo&quot;, &quot;Michelangelo&quot;, &quot;Raphael&quot;, &quot;Donatello&quot;])➞ [&quot;Raphael&quot;, &quot;Leonardo&quot;, &quot;Donatello&quot;, &quot;Michelangelo&quot;]

sort_by_length([&quot;Turing&quot;, &quot;Einstein&quot;, &quot;Jung&quot;])➞ [&quot;Jung&quot;, &quot;Turing&quot;, &quot;Einstein&quot;]

Notes

All test cases contain lists with strings of different lengths, so you won&#39;t have to deal with
multiple strings of the same length.

In [4]:
def sort_by_length(lst):
   return sorted(lst ,key= len)



print(f'sort_by_length(["Google", "Apple", "Microsoft"]) -> {sort_by_length(["Google", "Apple", "Microsoft"])}')
print(f'sort_by_length(["Leonardo", "Michelangelo", "Raphael", "Donatello"]) ->{sort_by_length(["Leonardo", "Michelangelo", "Raphael", "Donatello"])}')
print(f'sort_by_length(["Turing", "Einstein", "Jung"]) ->{sort_by_length(["Turing", "Einstein", "Jung"])}')

sort_by_length(["Google", "Apple", "Microsoft"]) -> ['Apple', 'Google', 'Microsoft']
sort_by_length(["Leonardo", "Michelangelo", "Raphael", "Donatello"]) ->['Raphael', 'Leonardo', 'Donatello', 'Michelangelo']
sort_by_length(["Turing", "Einstein", "Jung"]) ->['Jung', 'Turing', 'Einstein']

**Question5**

Create a function that validates whether three given integers form a Pythagorean triplet. The
sum of the squares of the two smallest integers must equal the square of the largest number to
be validated.


Examples

is_triplet(3, 4, 5) ➞ True
3² + 4² = 25
 5² = 25

is_triplet(13, 5, 12) ➞ True
 5² + 12² = 169
 13² = 169

is_triplet(1, 2, 3) ➞ False
1² + 2² = 5
 3² = 9

Notes
Numbers may not be given in a sorted order.

In [16]:
def is_triplet(lst):
  lst=list(lst)
  lst.sort()

  for i in lst:
     if lst[0]==i:
      a =i*i
     elif lst[1]==i:
      b=i*i
     elif lst[2]==i:
      c=i*i
      if a+b==c:
        return True
      else:
        return False

print(f'is_triplet((3, 4, 5)) ->{is_triplet((3, 4, 5)) }')
print(f'is_triplet((13, 5, 12))->{is_triplet((3, 4, 5)) }')
print(f'is_triplet((1,2,3)) ->{is_triplet((1,2,3))}')

is_triplet((3, 4, 5)) ->True
is_triplet((13, 5, 12))->True
is_triplet((1,2,3)) ->False